### ISSUE TITLE
小程序—未支付订单，是否可以增加一个”继续支付“ 的按钮

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#11]
如果客户有事情耽误了付款，未支付订单无法继续支付，只能重新选择，是否可以增加一个”继续支付“的按钮
![47051605507685_ pic](https://user-images.githubusercontent.com/74414333/99219324-55932e80-2817-11eb-816e-e4022585b257.jpg)

**Comment by lisaguo0** [comment]
如果12小时候自动取消订单，也没有问题，可以在客户取消订单时，在我的订单页面有个提示：”未支付订单将在12小时后自动关闭“
但是还有一种情况，是客户临时有事，没有支付，后面想支付时，在我的订单页面无法支付，只能重新去找订单和购买

**Comment by raul-sauco** [comment]
> 在我的订单页面无法支付，只能重新去找订单和购买

目前，就是这样，您要更改吗？

**Comment by lisaguo0** [comment]
可以修改成：在客户未支付的订单上，”删除“按钮旁边，再增加一个 ”继续支付“ 的按钮，如果超过12小时未支付，就关闭订单。

**Comment by raul-sauco** [comment]
可以
