### ISSUE TITLE
小程序—目前在小程序中，已经过去的活动时间，仍然可以报名，是否可以增加判断语句，时间过后，活动自动下架?

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#12]
![16211605507350_ pic_hd](https://user-images.githubusercontent.com/74414333/99218843-5d9e9e80-2816-11eb-8250-51a8a5daa384.jpg)

**Comment by lisaguo0** [comment]
是否可以调整为，小程序的不显示有两种方式，一种手动选择”不在小程序显示“，另外一种就是活动日期已过，该活动自动不显示，避免客户误报名

小程序的显示方式，就是手动选择”在小程序显示“

**Comment by raul-sauco** [comment]
当前，活动组具有一个属性（以小程序显示），可以为是或不是。
当我们必须决定要显示哪些程序时，我们可以检查该活动以及活动日期与当前日期，从而可以如下设置四个选项：

通过日期 | 显示标记 | 结果
---|---|---
不|不|不
是|不|不
不|是|是
是|是|是

我们可以根据需要进行调整，例如仅在日期未过去且标记设置为“显示”时才显示活动。

当标志设置为“显示”并且日期未过去时，简单的选项将显示单个事件。

看起来您想要更多的控制权，例如将 是/不 标志更改为具有更多选项的多选：

-从不显示
-仅在未通过日期时显示
-始终显示

可以这样做，但是会做更多工作，因为这意味着需要进行以下更改：

-数据库
-后端
-公共和私有API
-小程序
-测试

如果您想继续进行下去，请告诉我，我可以开始。

**Comment by lisaguo0** [comment]
其实我只需要在现有功能基础上，如果日期已经是从前的日期，则不管小程序选项是 ”显示“或”不显示“，该项目都自动不显示，这个功能实现起来工作量很大吗？

**Comment by raul-sauco** [comment]
日期过后不显示它们 很容易做。

**Comment by lisaguo0** [comment]
> 日期过后不显示它们 很容易做。

那就调整这一点就可以啦，辛苦

**Comment by lisaguo0** [comment]
后台日期she设置了11月24日，但是今天我看的时候小程序，显示“目前暂无活动”，是否跟关闭项目的时间点设置有关？
![47851606190123_ pic](https://user-images.githubusercontent.com/74414333/100046837-00c16a80-2e4c-11eb-9ecc-3ca1c8756aa2.jpg)


![屏幕快照 2020-11-24 上午11 53 36](https://user-images.githubusercontent.com/74414333/100046766-d7084380-2e4b-11eb-82b1-0ae3ab8fe249.png)

**Comment by raul-sauco** [comment]
可以预料的是，在24号，它将仅显示在24号“之前”启动的程序。 它会显示一个程序从23号开始，但是没有一个程序从24号开始。

您要显示同一天开始的程序吗？

**Comment by lisaguo0** [comment]
> 可以预料的是，在24号，它将仅显示在24号“之前”启动的程序。 它会显示一个程序从23号开始，但是没有一个程序从24号开始。
> 
> 您要显示同一天开始的程序吗？

所以，24日的活动，最晚显示持续到23日晚12点对吗？
如果确认是这样，就不用调整了

**Comment by raul-sauco** [comment]
> > 可以预料的是，在24号，它将仅显示在24号“之前”启动的程序。 它会显示一个程序从23号开始，但是没有一个程序从24号开始。
> > 您要显示同一天开始的程序吗？
> 
> 所以，24日的活动，最晚显示持续到23日晚12点对吗？
> 如果确认是这样，就不用调整了

是的，现在就是这样。 如果您想更改它，那将很容易。

我添加了一个示例[项目](https://backend.minihiker.com/weapp/1350)，可以随意使用日期查看不同的结果。

**Comment by lisaguo0** [comment]
> > > 可以预料的是，在24号，它将仅显示在24号“之前”启动的程序。 它会显示一个程序从23号开始，但是没有一个程序从24号开始。
> > > 您要显示同一天开始的程序吗？
> > 
> > 
> > 所以，24日的活动，最晚显示持续到23日晚12点对吗？
> > 如果确认是这样，就不用调整了
> 
> 是的，现在就是这样。 如果您想更改它，那将很容易。
> 
> 我添加了一个示例[项目](https://backend.minihiker.com/weapp/1350)，可以随意使用日期查看不同的结果。

算了，先不改了，先改其他重要性排序靠前的项目吧
