### ISSUE TITLE
小程序—一个小问题：”账户微信编号“ 请同事测试时都不太懂，麻烦把文字改成 ”微信号（非微信昵称）“  ，另外同事在测试时发现，填写账户名称信息，但是无法更新，操作视频无法上传，我微信给你

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#13]
![17901605842183_ pic_hd](https://user-images.githubusercontent.com/74414333/99753916-3f8cb300-2b22-11eb-8ee8-7de46a76410c.jpg)

**Comment by lisaguo0** [comment]
目前我测试微信名称修改，还是无法更新

**Comment by raul-sauco** [comment]
我尚未发送任何更新，该更新将在1.1.3中修复

**Comment by lisaguo0** [comment]
我昨天测试时，账户的用户名、微信和头像会延迟更新，但是今天修改后，又不更新了，如果这个问题解决起来麻烦，可以稍后解决，先解决紧急问题

**Comment by raul-sauco** [comment]
bafc711 Update to always refresh info from the server on account detail update. Update to refresh account info `onShow` instead of `onLoad`.
