### ISSUE TITLE
关于小程序的问题，先重点修复以下几个问题即可

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#15]
1、后台日期设置了11月24日，但是今天我看的时候小程序，显示“目前暂无活动”，是否跟关闭项目的时间点设置有关？需要修改成活动日期当天时间7点以前都可以拍
https://github.com/raul-sauco/minihiker-weapp/issues/12

2、小程序—未支付订单，是否可以增加一个”继续支付“ 的按钮 （这个功能需要增加，但是重要性可以靠后一些，等小程序第一版面向客户使用后，可能会有问题，之后一起集中修改即可）
https://github.com/raul-sauco/minihiker-weapp/issues/11

**Comment by raul-sauco** [comment]
让我们为一个问题线程保留问题。 为了管理问题的优先级，我刚刚创建了一个[董事会](https://github.com/raul-sauco/minihiker-weapp/projects/1?add_cards_query=is%3Aopen)。 我还将添加一个可以使用的“紧急”标签。
