### ISSUE TITLE
小程序—在设置项目时，发现放在焦点图的标题，显示不全

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#22]
![49141607918284_ pic](https://user-images.githubusercontent.com/74414333/102039412-aab96480-3e04-11eb-9313-c4c341b2eedb.jpg)

**Comment by raul-sauco** [comment]
图像文档在[这里](https://developers.weixin.qq.com/miniprogram/dev/component/image.html) @lisaguo0 请看一下为什么会这样。

我认为横幅广告必须具有固定的高度，否则当项目更改时，屏幕会上下颠簸。

但是您使用的图像大小不同，因此，我们需要对其进行裁剪。

现在，我们使用的是“ aspectFill”，固定高度为200px，通常约为移动设备屏幕的五分之一。如果使用较高的图像，则会裁切侧面，而使用较宽的图像，则会裁切顶部和底部。

如果您阅读了我发送的文档，则有许多不同的处理方法，可以告诉我您是否认为另一种方法可以更好地工作，我们可以尝试一下。

标语图像的正常工作流程是使标语具有固定的宽高比，并确保所有图像均以该宽高比显示。 但是我想我们之前已经讨论过，您更喜欢使用自由宽高比。

**Comment by raul-sauco** [comment]
<search-bar-clear> is 0 height in `pages/index` the banner rolls up into it.
