### ISSUE TITLE
后台—小程序里有一些客户不改昵称，进入后台后的昵称就是字母和数字组合，是否有办法自动读取微信昵称？这一点是在测试合同时发现的

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#6]
![屏幕快照 2020-11-16 下午2 43 04](https://user-images.githubusercontent.com/74414333/99220759-35b13a00-281a-11eb-80ea-1b60ece0e1af.png)
![屏幕快照 2020-11-16 下午2 44 34](https://user-images.githubusercontent.com/74414333/99220807-524d7200-281a-11eb-8080-738ff0d11fb3.png)

**Comment by lisaguo0** [comment]
同事测试时，这里的必填信息都是空的
![16541605509019_ pic_hd](https://user-images.githubusercontent.com/74414333/99220925-95a7e080-281a-11eb-914f-1f8b072e5716.jpg)

**Comment by raul-sauco** [comment]
> 是否有办法自动读取微信昵称？

唯一的方法是使用 [getUserInfo](https://developers.weixin.qq.com/miniprogram/en/dev/api/open-api/user-info/wx.getUserInfo.html)，这需要用户查看 “授权访问我的信息”对话框。

首先，我在**之后**放置了该对话框，例如，当用户想要发送常见问题解答时，我们需要使用该信息，但是随后我被要求将对话框放在流程的开始，这是用户的第一个屏幕 锯。

我们让它运行了一段时间，但随后微信更改了要求，并且不再允许在显示某些应用页面之前向用户询问用户信息。 因此，我们的“发布审核”之一失败了。 我们讨论了该问题，并决定将其全部删除，因此现在我们无权访问用户名和个人资料图片。

**Comment by raul-sauco** [comment]
![330436909](https://user-images.githubusercontent.com/5407332/99518601-14268e80-2991-11eb-9ac0-fae330fd1ea0.jpg)

这是我们正在使用的屏幕。

根据新的小程序规定，我们不能再将其显示为第一个屏幕。 我们需要有条件地将其添加到我们要使用获得的信息（例如用户名）的页面上。

但是现在将其重新带回将意味着大量的工作时间，因为我已经将小程序和后端更改为**不使用** getUserInfo提供的信息。

**Comment by raul-sauco** [comment]
如果您需要用户名，我们可能需要先更新用户名，然后才能使用某些功能。

**Comment by lisaguo0** [comment]
这个功能是否可以增加？或者在客户登陆小程序时，自动申请可以使用他的昵称

**Comment by raul-sauco** [comment]
> 这个功能是否可以增加？或者在客户登陆小程序时，自动申请可以使用他的昵称

申请可以使用他的昵称会更好

**Comment by lisaguo0** [comment]
好的，谢谢

> > 这个功能是否可以增加？或者在客户登陆小程序时，自动申请可以使用他的昵称
> 
> 申请可以使用他的昵称会更好

**Comment by raul-sauco** [comment]
FYI: Documentation about why we removed the calls to `getUserInfo()` is [on the Wechat developer pages](https://developers.weixin.qq.com/community/operate/doc/000640bb8441b82900e89f48351401)

**Comment by raul-sauco** [comment]
1-当要求客户输入姓名时，我们应该显示什么消息？
2-我们应该在哪里显示消息？
