### ISSUE TITLE
小程序—补充信息时，性别信息即使填写了，也需要再选择一次，否则就 报错

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#7]
![47011605505538_ pic](https://user-images.githubusercontent.com/74414333/99217127-4b226600-2812-11eb-9f5e-e706ccf8f0bf.jpg)

**Comment by raul-sauco** [comment]
Fixed updating null field check from `if (!field) {...}` to `if (field === null || field === '') {...}` to prevent `gender=0` triggering a false positive.
