### ISSUE TITLE
小程序&后台——因为担心小程序描述界面的图片可能有问题，我尝试增加跳转到公众号文章的超链接，但是在后台可以添加，但是在小程序端无法跳转

### ISSUE THREAD

**Issue by lisaguo0** [raul-sauco/minihiker-weapp#8]
![后台超链接可以跳转](https://user-images.githubusercontent.com/74414333/99222803-49f73600-281e-11eb-8914-1b2c55973377.png)
![47071605510578_ pic](https://user-images.githubusercontent.com/74414333/99222920-7ca12e80-281e-11eb-945a-38f69990c554.jpg)

**Comment by lisaguo0** [comment]
我试着做了个二维码，在小程序端也没有反应
![47081605511019_ pic](https://user-images.githubusercontent.com/74414333/99223111-dbff3e80-281e-11eb-8a77-0f9dff903afd.jpg)

**Comment by raul-sauco** [comment]
> 我尝试增加跳转到公众号文章的超链接，但是在后台可以添加，但是在小程序端无法跳转

QR码只是图像。 我们在小程序上所能做的就是显示图像。 这将取决于您在该QR码上单击以对其进行处理的应用程序。

微信选择不让您直接根据*场景条件*从迷你程序打开公共帐户QR码。 我们无法控制它或更改QR码在小程序中的行为。

看看[official-account](https://developers.weixin.qq.com/miniprogram/dev/component/official-account.html) 文档，以了解其解释。

**Comment by lisaguo0** [comment]
好的，明白了
